### ISSUE TITLE
Default configs of Black and flake8 have conflicts

### ISSUE THREAD

**Issue by hukkin** [interrogator/sire#1]
Currently flake8 and Black run with default configs, neither of them has a config file. The defaults of these tools have conflicts, e.g. the line length (Black formats longer lines than flake8 wants), and at least the checks W503 and E203 of flake8.

To fix this, this resource could be helpful: https://github.com/python/black#line-length

**Comment by interrogator** [comment]
I believe this is fixed by addition of .flake8, e.g. https://github.com/interrogator/sire/blob/master/templates/.flake8 ?

**Comment by hukkin** [comment]
yup
